# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 385e698a9ffd62eb10553121fd4d21457696e13a6735d6910fe09a734dc5e5bf7bdd66ee15069368c978ac4d2646cee2d084fe8ab92471643de557457e1e4689
  aws:
    access_key_id: "AKIAJHQQAHUJFVG4COBQ"
    secret_access_key: "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"
    lambda:
      role: "arn:aws:iam::675424637592:role/functions-role-development"

test:
  secret_key_base: ac1ec1095e2f5d3e5c19db96bb1b4579cb9bc186c423faebac5458239a1c719aa1b439b8b9f361c93c42b934c13749189e193d966844c96087d52f954e99e937
  aws:
    access_key_id: ""
    secret_access_key: ""
    lambda:
      role: ""

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    lambda:
      role: <%= ENV["AWS_LAMBDA_ROLE"] %>
